// 고양이와 개는 몇 마리 있을까
SELECT ANIMAL_TYPE, COUNT(ANIMAL_TYPE) as 'count'
FROM ANIMAL_INS
WHERE ANIMAL_TYPE = 'Cat' or ANIMAL_TYPE = 'Dog'
GROUP BY ANIMAL_TYPE
ORDER BY ANIMAL_TYPE

// 루시와 엘라 찾기 
SELECT ANIMAL_ID, NAME, SEX_UPON_INTAKE
FROM ANIMAL_INS
WHERE NAME = 'Lucy' or NAME = 'Ella' or NAME =  'Pickle' or NAME = 'Rogan' or NAME = 'Sabrina' or NAME = 'Mitty'
ORDER BY ANIMAL_ID

// 동명 동물 수 찾기
SELECT NAME, COUNT(NAME) as 'COUNT'
FROM ANIMAL_INS 
WHERE NAME IS NOT NULL
GROUP BY NAME HAVING COUNT(NAME) > 1
ORDER BY NAME

// 최솟값 구하기
SELECT DATETIME as '시간'
FROM ANIMAL_INS
ORDER BY DATETIME
LIMIT 1

// 이름에 el이 들어가는 동물 찾기
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE NAME LIKE "%EL%" AND ANIMAL_TYPE = 'Dog' ORDER BY NAME ASC

// 동물 수 구하기 
SELECT COUNT(*) as 'count'
FROM ANIMAL_INS

// 입양 시각 구하기 (1)
SELECT HOUR(DATETIME) HOUR, COUNT(DATETIME) COUNT
FROM ANIMAL_OUTS
GROUP BY HOUR(DATETIME)
HAVING HOUR >= 9 and HOUR <= 19

// NULL 처리하기
SELECT ANIMAL_TYPE, IFNULL(NAME, 'No name'), SEX_UPON_INTAKE
FROM ANIMAL_INS
ORDER BY ANIMAL_ID

// 중성화 여부 파악하기
SELECT ANIMAL_ID, NAME,	CASE WHEN SEX_UPON_INTAKE LIKE "%Neutered%" OR SEX_UPON_INTAKE LIKE "%Spayed%" THEN "O" ELSE 'X' END AS "중성화"
FROM ANIMAL_INS

// 중복 제거하기
SELECT COUNT(DISTINCT NAME) as 'count'
FROM ANIMAL_INS
WHERE NAME IS NOT NULL

// DATETIME에서 DATE로 형 변환
SELECT ANIMAL_ID, NAME, DATE_FORMAT(DATETIME, '%Y-%m-%d') AS 날짜
FROM ANIMAL_INS
ORDER BY ANIMAL_ID
